---
title: Your awesome title
timezone: UTC
collections:
  awards:
    title: Awards
    output: false
  carousel:
    title: Carousel
    output: false
  events:
    title: Events
    output: false
  leadership:
    title: Leadership
    output: true
    permalink: "/about-us/leadership/:name"
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
  success_stories:
    title: Success stories
    output: false
  blog_tags:
    title: Tags
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:year/:month/:title"
    layout: post
    image: 
    description: 
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
- scope:
    path: ''
    type: leadership
  values:
    layout: profile
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: https://dcscores.org
enforce_ssl: dcscores.org
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
excerpt_separator: |2+



future: true
permalink: pretty
sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%b %d, %Y"
gems:
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- Gruntfile.js
- package.json
- README.markdown
- node_modules
- ".gitignore"
